const ADD_STUDENT = 'ADD_STUDENT';
const UPDATE_STUDENTS = 'UPDATE_STUDENTS';
const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT';
const DELETE_STUDENT = 'DELETE_STUDENT';

export { ADD_STUDENT, UPDATE_STUDENTS, SET_SELECTED_STUDENT, DELETE_STUDENT };